const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..'),pub=path.join(root,'public');
let n=0;const ok=(x,m)=>{assert.ok(x,m);n++};
const must=['public/app.js','public/core/storage.js','public/core/shell.js','public/style.css','public/service-worker.js','public/runtime.js','lib/engine.js','lib/studio.js','lib/versions.js','package.json'];
for(const rel of must)ok(fs.existsSync(path.join(root,rel)),rel);
const app=fs.readFileSync(path.join(pub,'app.js'),'utf8');
const storage=fs.readFileSync(path.join(pub,'core','storage.js'),'utf8');
const shell=fs.readFileSync(path.join(pub,'core','shell.js'),'utf8');
ok(app.includes('FloraLabRuntime.request'),'runtime client used');
ok(app.includes('FloraLabStorage.create'),'app uses storage module');
ok(!app.includes('indexedDB.open'),'IndexedDB implementation removed from app');
ok(storage.includes('indexedDB.open'),'storage module owns IndexedDB');
ok(storage.includes("STATE_KEY='floralab-studio-state'"),'stable storage key is version-independent');
ok(storage.includes("LEGACY_STATE_KEYS=['floralab-1.1'"),'legacy storage keys remain migratable');
ok(app.includes('restoreBackup:restoreLocalBackup'),'app restores through storage module');
ok(!app.includes("floralab-1.1-backup"),'app no longer owns legacy backup keys');
ok(app.includes('FloraLabShell.create'),'app uses shell module');
const singleQueryIteration=app.replaceAll('$(','__ALL__(');
ok(!/\$\([^)]*\)\.forEach/.test(singleQueryIteration),'single query selector is never iterated');
ok(!app.includes('block_cat'),'internal pet-risk enum is not rendered by app');
ok(shell.includes("$('[data-go]').forEach"),'shell binds every navigation action');
ok(app.includes("$$('[data-tab]').forEach"),'all workspace tabs are bound');
ok(app.includes("['render','效果图']"),'Render workspace remains present');
ok(shell.includes('data-go="render"'),'Render has a discoverable top-level entry');
ok(app.includes('assets/hero-render-study.webp'),'approved landing cover remains wired');
ok(!app.includes("version:'1.3.1'"),'app does not hard-code a release version');
const studioSource=fs.readFileSync(path.join(root,'lib','studio.js'),'utf8');
const versions=require(path.join(root,'lib','versions.js'));
ok(versions.HANDOFF_SCHEMA==='floralab/1.0','handoff schema constant');
ok(versions.BLUEPRINT_VERSION==='2.0','Blueprint version constant');
ok(versions.RENDER_SPEC_VERSION==='1.0','Render Spec version constant');
ok(!studioSource.includes("schema:'floralab/1.0'"),'Studio uses shared schema constant');
const runtime=fs.readFileSync(path.join(pub,'runtime.js'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
ok(runtime.includes(`version:${JSON.stringify(pkg.version)}`),'runtime version follows package');
ok(runtime.includes("mode:'zero-api-pwa'"),'zero API runtime preserved');
ok(runtime.includes('buildRenderSpec'),'Render Spec bundled');
ok(runtime.includes('/api/design/update-blueprint'),'Blueprint update route bundled');
const sw=fs.readFileSync(path.join(pub,'service-worker.js'),'utf8');
ok(sw.includes('NETWORK_FIRST'),'PWA shell refresh policy preserved');
ok(sw.includes(`floralab-${pkg.version}-shell-refresh`),'service worker cache follows package');
ok(pkg.scripts['check:fast'].includes('test:fast-contract'),'fast contract wired');
ok(pkg.scripts['test:release'],'release gate remains separate');
console.log(`fast-contract: ${n} checks passed`);
