const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..'),pub=path.join(root,'public');
let n=0;const ok=(x,m)=>{assert.ok(x,m);n++};
const must=['public/app.js','public/style.css','public/service-worker.js','public/runtime.js','lib/engine.js','lib/studio.js','package.json'];
for(const rel of must)ok(fs.existsSync(path.join(root,rel)),rel);
const app=fs.readFileSync(path.join(pub,'app.js'),'utf8');
ok(app.includes('FloraLabRuntime.request'),'runtime client used');
ok(app.includes("$$('[data-go]').forEach"),'all navigation actions are bound');
ok(app.includes("$$('[data-tab]').forEach"),'all workspace tabs are bound');
ok(app.includes("['render','效果图']"),'Render workspace remains present');
ok(app.includes('data-go="render"'),'Render has a discoverable top-level entry');
ok(app.includes('assets/hero-render-study.webp'),'approved landing cover remains wired');
ok(!app.includes("version:'1.3.1'"),'app does not hard-code a release version');
const runtime=fs.readFileSync(path.join(pub,'runtime.js'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
ok(runtime.includes(`version:${JSON.stringify(pkg.version)}`),'runtime version follows package');
ok(runtime.includes("mode:'zero-api-pwa'"),'zero API runtime preserved');
ok(runtime.includes('buildRenderSpec'),'Render Spec bundled');
ok(runtime.includes('/api/design/update-blueprint'),'Blueprint update route bundled');
const sw=fs.readFileSync(path.join(pub,'service-worker.js'),'utf8');
ok(sw.includes('NETWORK_FIRST'),'PWA shell refresh policy preserved');
ok(sw.includes(`floralab-${pkg.version}-shell-refresh`),'service worker cache follows package');
ok(pkg.scripts['check:fast'].includes('test:fast-contract'),'fast contract wired');
ok(pkg.scripts['test:release'],'release gate remains separate');
console.log(`fast-contract: ${n} checks passed`);
