const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..'),pub=path.join(root,'public');
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++};
const catalog=JSON.parse(fs.readFileSync(path.join(root,'data','catalog.json'),'utf8'));
const visuals=JSON.parse(fs.readFileSync(path.join(root,'data','material-visuals.json'),'utf8'));
const visualQueries=JSON.parse(fs.readFileSync(path.join(root,'data','material-visual-queries.json'),'utf8'));
ok(catalog.flowers.length===117,'117 flower entries');
ok(catalog.creative.length===13,'13 creative entries');
ok(Object.keys(visualQueries.items||{}).length===130,'130 material visual queries');
for(const id of [...catalog.flowers.map(x=>'flower:'+x.id),...catalog.creative.map(x=>'creative:'+x.id)])ok(Boolean(visualQueries.items?.[id]?.query),`visual query ${id}`);
const ids=[...catalog.flowers.map(x=>'flower:'+x.id),...catalog.creative.map(x=>'creative:'+x.id)];
ok(new Set(ids).size===ids.length,'material ids unique');
const flowerFields=['id','name','aliases','colors','price','availability','season','stem_cm','head_cm','weight','stem_strength','water_need','fragility','beginner','roles','foam_fit','vase_fit','notes','peak_months','market_tier','substitutes','pet_risk'];
for(const key of flowerFields)ok(catalog.flowers.every(x=>Object.prototype.hasOwnProperty.call(x,key)),`flower field ${key}`);
ok(catalog.flowers.some(x=>x.reference_only),'reference entries exist');
ok(catalog.flowers.filter(x=>x.reference_only).every(x=>String(x.notes||'').length>0),'reference entries explain uncertainty');
ok(catalog.flowers.filter(x=>x.reference_only).every(x=>Object.prototype.hasOwnProperty.call(x,'pet_risk')),'reference pet field explicit');
const names=new Set();for(const f of catalog.flowers){names.add(f.name);for(const a of f.aliases||[])names.add(a);}
const genericSubs=new Set(['其他常见叶材','大叶材']);
const unresolved=[];for(const f of catalog.flowers)for(const sub of f.substitutes||[])if(!names.has(sub)&&!genericSubs.has(sub))unresolved.push(`${f.name}->${sub}`);
ok(unresolved.length===0,'substitutes resolve or are explicit generic categories: '+unresolved.join(','));
ok(visuals.version==='1.2.0','visual registry version');
ok(visuals.policy&&String(visuals.policy.rule).includes('verified'),'visual verification policy');
for(const [id,v] of Object.entries(visuals.items||{})){if(v.verified){ok(Boolean(v.asset),`${id} verified asset`);ok(Boolean(v.source),`${id} verified source`);ok(Boolean(v.license),`${id} verified license`);}}
const studio=fs.readFileSync(path.join(root,'lib','studio.js'),'utf8');
for(const key of ['stem_cm','head_cm','weight','stem_strength','fragility','peak_months','market_tier'])ok(studio.includes(key),`public catalog exposes ${key}`);
ok(studio.includes("beginner:f.beginner===true?true:(f.beginner===false?false:null)"),'public catalog preserves unknown beginner state');
const library=fs.readFileSync(path.join(pub,'library.js'),'utf8');
ok(library.includes('FloraLabLibrary'),'library module built');
ok(library.includes('commonsVisual'),'Commons visual resolver');
ok(library.includes('Wikimedia Commons'),'Commons attribution surface');
ok(library.includes('不使用生成图冒充材料事实'),'no fake identification visual');
ok(library.includes('reference_only'),'reference handling');
ok(library.includes('season-timeline'),'season timeline');
ok(library.includes('substitutes'),'substitute navigation');
ok(library.includes('currentUse'),'current project context');
ok(library.includes('petRiskInfo'),'pet risk normalization');
ok(library.includes('猫环境高风险'),'cat high-risk user-facing label');
ok(library.includes('宠物信息需核实'),'unknown pet risk user-facing label');
ok(library.includes("food?'食品'"),'creative food search');
const app=fs.readFileSync(path.join(pub,'app.js'),'utf8');
ok(app.includes('FloraLabLibrary.render'),'app loads library module');
ok(app.includes('recipe-material-link'),'Recipe links to detail');
ok(app.includes("fetch('./data/material-visuals.json'"),'visual provenance registry loaded');
const index=fs.readFileSync(path.join(pub,'index.html'),'utf8');
ok(index.includes('./library.js'),'library script linked');
ok(!index.includes('\\n'),'public shell has no visible escape artifact');
const sw=fs.readFileSync(path.join(pub,'service-worker.js'),'utf8');
ok(sw.includes("'./library.js'"),'library offline shell');
ok(sw.includes("'./data/material-visuals.json'"),'visual registry offline shell');
ok(sw.includes("'./data/material-visual-queries.json'"),'visual query manifest offline shell');
console.log(`library-1.2: ${n} checks passed`);
