const fs=require('fs'),path=require('path'),assert=require('assert');
const Studio=require('../lib/studio');
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','catalog.json'),'utf8'));
let n=0;const ok=(x,m)=>{assert.ok(x,m);n++};
const input={mode:'floral',type:'花束',colors:['紫色','白色'],budget:360,budgetPriority:'balance',style:'自然、温柔',existing:'',size:'medium',designMonth:9,region:'',preferred:'玫瑰、绣球',avoid:'',petContext:'',mechanicPreference:''};
const plan=Studio.createStudioPlan(catalog,input);
const spec=Studio.buildRenderSpec(plan);
ok(spec.version==='1.0','Render Spec version');
ok(spec.purpose==='effect-render-handoff','Render purpose');
ok(!Object.prototype.hasOwnProperty.call(plan,'render'),'Render is not duplicated into editable plan state');
ok(spec.materials.length>0,'Render materials exist');
for(const m of spec.materials){const r=plan.recipe.find(x=>x.key===m.key);ok(r&&Number(r.quantity)===Number(m.quantity),`Recipe quantity is authoritative for ${m.key}`);}
ok(spec.hard_constraints.includes('Recipe 数量'),'Recipe quantity locked');
ok(spec.structure&&spec.structure.silhouette&&spec.structure.height_layers&&spec.structure.depth_layers,'structure summary exists');
ok(Array.isArray(spec.self_check)&&spec.self_check.length>=6,'self check exists');
ok(!JSON.stringify(spec).includes('还原率'),'no fake fidelity percentage');
const handoff=Studio.handoffObject(plan);
ok(handoff.render&&handoff.render.version==='1.0','handoff exports Render Spec');
ok(handoff.recipe===plan.recipe,'handoff keeps original Recipe');
ok(!Object.prototype.hasOwnProperty.call(handoff.plan,'render'),'nested plan remains source-only');
const row=plan.recipe.find(x=>['flower','creative'].includes(x.kind)&&x.quantity>0);
const changed=Studio.updateRecipe(catalog,plan,[{key:row.key,quantity:row.quantity+1,owned:row.owned,unit_price:row.unit_price}]);
const changedSpec=Studio.buildRenderSpec(changed),changedMat=changedSpec.materials.find(x=>x.key===row.key);
ok(changedMat.quantity===row.quantity+1,'Render quantity follows Recipe edits');
const node=changed.blueprint.nodes[0],before=Studio.buildRenderSpec(changed).structure.visual_mass.x_cm;
const moved=Studio.updateBlueprint(catalog,changed,{type:'set',id:node.id,x:Number(node.x||0)+4});
const after=Studio.buildRenderSpec(moved).structure.visual_mass.x_cm;
ok(before!==after,'Render structure follows Blueprint edits');
const text=Studio.renderHandoffText(changed);
ok(text.includes('【硬约束｜不得擅自改变】'),'handoff text has hard constraints');
ok(text.includes(row.name),'handoff text names material');
ok(text.includes(`× ${row.quantity+1}${row.unit}`),'handoff text carries exact Recipe count');
ok(text.includes('生成后自检'),'handoff text has self check');
const stale=Studio.handoffObject(plan);stale.render.materials[0].quantity+=3;
const validation=Studio.validateImportObject(stale,catalog);
ok(validation.ok,'stale Render does not block source-compatible import');
ok(validation.warnings.some(x=>x.includes('Render Spec 与 Recipe 数量不一致')),'stale Render mismatch is warned');
const old=Studio.handoffObject(plan);delete old.render;
const oldV=Studio.validateImportObject(old,catalog),migrated=Studio.migratePlan(catalog,old),regen=Studio.handoffObject(migrated);
ok(oldV.ok,'old 1.0 file without Render remains valid');
ok(regen.render&&regen.render.materials.length>0,'old file regenerates Render on export');
console.log(`render-1.3: ${n} checks passed`);
