const fs = require('fs');
const path = require('path');
const { bundle } = require('./bundle-commonjs');
const ROOT = path.resolve(__dirname, '..');
const pkg = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')
);
const { code, modules } = bundle({
  root: ROOT,
  entry: 'browser/runtime-entry.js',
  externals: { crypto: 'browser/crypto-shim.js' }
});
const runtime = `// Generated by scripts/build-runtime.js. Edit browser/ and lib/ sources.\n(function(){\n'use strict';\n${code}\nwindow.FloraLabRuntime=entry.createBrowserRuntime({fetch:window.fetch.bind(window),baseUrl:document.baseURI,version:${JSON.stringify(pkg.version)}});\n})();\n`;
fs.writeFileSync(path.join(ROOT, 'public', 'runtime.js'), runtime);
console.log(`Bundled ${modules.length} runtime modules`);
fs.mkdirSync(path.join(ROOT, 'public', 'data'), { recursive: true });
fs.copyFileSync(
  path.join(ROOT, 'data', 'catalog.json'),
  path.join(ROOT, 'public', 'data', 'catalog.json')
);
fs.copyFileSync(
  path.join(ROOT, 'data', 'material-visuals.json'),
  path.join(ROOT, 'public', 'data', 'material-visuals.json')
);
fs.copyFileSync(
  path.join(ROOT, 'data', 'material-visual-queries.json'),
  path.join(ROOT, 'public', 'data', 'material-visual-queries.json')
);
const libraryPartDir = path.join(ROOT, 'data', 'library-source-parts');
const libraryParts = fs
  .readdirSync(libraryPartDir)
  .filter((x) => x.startsWith('library.part.'))
  .sort();
if (!libraryParts.length)
  throw new Error('FloraLab 1.2 library source is missing');
fs.writeFileSync(
  path.join(ROOT, 'public', 'library.js'),
  libraryParts
    .map((x) => fs.readFileSync(path.join(libraryPartDir, x), 'utf8'))
    .join('')
);
fs.mkdirSync(path.join(ROOT, 'project-kit'), { recursive: true });
fs.copyFileSync(
  path.join(ROOT, 'data', 'catalog.json'),
  path.join(ROOT, 'project-kit', 'FLOWER_CATALOG_1_1.json')
);
console.log('browser runtime built');
