import json,os,shutil,subprocess,socket,atexit,time
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];URL=os.getenv('FLORALAB_BASE_URL','http://127.0.0.1:4173/floralab/');checks=[]
if not os.getenv('FLORALAB_BASE_URL'):
 try:
  with socket.create_connection(('127.0.0.1',4173),timeout=1):pass
 except OSError:
  server=subprocess.Popen([shutil.which('node'),'scripts/static-server.js'],cwd=ROOT,stdout=subprocess.DEVNULL);atexit.register(server.terminate);time.sleep(1)
with sync_playwright() as pw:
 chrome=os.getenv('FLORALAB_BROWSER') or shutil.which('google-chrome') or shutil.which('chromium') or r'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'
 b=pw.chromium.launch(executable_path=chrome,headless=True,args=['--no-sandbox']);page=b.new_page();page.route('**/storage-seed',lambda r:r.fulfill(body='<html><body>Storage migration test</body></html>',content_type='text/html'));page.goto(URL+'storage-seed')
 page.add_script_tag(url=URL+'runtime.js');page.add_script_tag(url=URL+'core/storage.js')
 seed=page.evaluate('''async()=>{const p=await FloraLabRuntime.request('/api/design/generate',{method:'POST',body:JSON.stringify({prompt:'白色桌花'})});const value={plan:p,form:p.request,mode:'floral',lastTab:'build',updatedAt:new Date().toISOString()};const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('floralab-studio',1);r.onupgradeneeded=()=>{r.result.createObjectStore('projects',{keyPath:'id'});r.result.createObjectStore('meta',{keyPath:'key'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});await new Promise((resolve,reject)=>{const tx=db.transaction(['projects','meta'],'readwrite');tx.objectStore('projects').put({id:p.id,title:p.title,updatedAt:value.updatedAt,state:value});tx.objectStore('meta').put({key:'current',planId:p.id});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();localStorage.setItem('floralab-studio-state',JSON.stringify(value));return p.id}''')
 page.goto(URL,wait_until='networkidle');page.locator('#newDesign').wait_for()
 result=page.evaluate('''async(seed)=>{const checks=[],test=(x,m)=>{if(!x)throw new Error(m);checks.push(m)};const loaded=JSON.parse(localStorage.getItem('floralab-studio-state'));test(loaded.plan.id===seed,'DB v1 original survives upgrade');const state={...loaded,projects:[],selections:{}};const store=FloraLabStorage.create({state,cleanTitle:String});await store.load();const db=await store.openDB();test(db.version===2&&db.objectStoreNames.contains('media')&&db.objectStoreNames.contains('revisions'),'DB v2 stores created');db.close();await store.commitPlan({...state.plan,title:'Before failure'});const original=JSON.stringify(state.plan),key=state.plan.id;
const transact=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(names,mode,...rest){const tx=transact.call(this,names,mode,...rest);if(mode==='readwrite')queueMicrotask(()=>tx.abort());return tx};try{await store.commitPlan({...state.plan,title:'Must not save'},{assets:[{id:'failed-asset',blob:new Blob(['test'])}]});throw new Error('failed transaction accepted')}catch(e){test(JSON.stringify(state.plan)===original,'failed atomic commit keeps current plan')}finally{IDBDatabase.prototype.transaction=transact}test(!(await store.idbGet('media','failed-asset')),'failed transaction leaves no orphan image');test((await store.idbGet('projects',key)).state.plan.title==='Before failure','failed transaction preserves saved project');test(state.saveStatus.tone==='error','failure status is explicit');
await store.commitPlan({...state.plan,title:'After change'});const snapshots=await store.revisions(key);test(snapshots.some(x=>x.state.plan.title==='Before failure'),'previous state snapshotted');await store.restoreBackup(snapshots.find(x=>x.state.plan.title==='Before failure'));test(state.plan.title==='Before failure','restore exact target');test((await store.revisions(key)).some(x=>x.state.plan.title==='After change'),'restore preserves state it replaced');
const open=indexedDB.open.bind(indexedDB),set=Object.getPrototypeOf(localStorage).setItem;indexedDB.open=function(){const r={error:new Error('quota test')};queueMicrotask(()=>r.onerror());return r};Object.getPrototypeOf(localStorage).setItem=function(){throw new Error('quota test')};try{await store.save();throw new Error('false success')}catch(e){test(state.saveStatus.tone==='error','both stores fail visibly')}finally{indexedDB.open=open;Object.getPrototypeOf(localStorage).setItem=set}await store.save();test(state.saveStatus.tone==='saved','save recovers after storage returns');return checks}''',seed)
 checks+=result;b.close()
print(json.dumps({'storage_checks':len(checks),'checks':checks},ensure_ascii=False))
